import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Provider_react_query from '@/Components/porvider/Provider_react_query'
import { Toaster } from "@/Components/ui/toaster"
import {GoogleOAuthProvider} from '@react-oauth/google';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
         
       <GoogleOAuthProvider clientId="1057249070232-hkc7e3b8398ftii8n8uocu71ktiv66oi.apps.googleusercontent.com">
        <Provider_react_query>
        {children}
        <Toaster />
        </Provider_react_query>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
